version: "3"
services:
        calculator:
                image: localhost:5000/jiyun0524/calculator:latest
                ports:
                       - "8090"
        redis:
                image: redis:latest
